apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dormwatch-front
  namespace: dormwatch-front
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: dormwatch.thesis-i.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dormwatch-front
                port:
                  number: 80
